# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main


pool:
  vmImage: ubuntu-latest

variables:
- group: MJKG_API_SETTINGS
- name: buildConfiguration
  value: Release


stages:

- stage: 'Development'
  jobs:
  - deployment: 'DeployToDevelopment'
    environment: 'Approval_API_Dev'
    strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  dir
                  
              - checkout: self
              - task: UseDotNet@2
                displayName: Install .NET Core SDK
                inputs:
                  version: 3.1.x
                  packageType: runtime

              - task: PowerShell@2
                displayName: Replace Settings
                inputs:
                  targetType: 'inline'
                  script: |
                    cd FeatureFlagsCo.APIs/FeatureFlags.APIs
                    $pathToJson = "appsettings.json"
                    $a = Get-Content $pathToJson | ConvertFrom-Json
            
                    $a.ConnectionStrings.ConnStr = "$(SQLDATABASE_ConnectionString_Dev)"
                    $a.ConnectionStrings.RedisServerUrl = "$(REDISCACHE_ConnectionString_Dev)"
                    $a.JWT.Secret = "$(JWT_Secret_Dev)"
                    $a.CosmosDb.Account = "$(CosmosDb_Account_Dev)"
                    $a.CosmosDb.Key = "$(CosmosDb_Key_Dev)"
                    $a.CosmosDb.DatabaseName = "$(CosmosDb_Account_DatabaseName)"
                    $a.CosmosDb.ContainerName = "$(CosmosDb_Account_ContainerName)"

                    $a.ApplicationInsights.InstrumentationKey = "$(AppInsights_InstrumentationKey_Dev)"
                    $a.ApplicationInsights.ConnectionString = "$(AppInsights_ConnectionString_Dev)"
                    $a.MySettings.AppInsightsApplicationId = "$(AppInsights_ApplicationId_Dev)"
                    $a.MySettings.AppInsightsApplicationApiSecret = "$(AppInsights_ApplicationApiSecret_Dev)"

                    $a.MySettings.SendCloudAPIUser = "$(SendCloudAPIUser)"
                    $a.MySettings.SendCloudAPIKey = "$(SendCloudAPIKey)"
                    $a.MySettings.SendCloudFrom = "noreply@feature-flags.co"
                    $a.MySettings.SendCloudFromName = "feature-flags.co"
                    $a.MySettings.SendCloudTemplate = "forgetpassword"
                    $a.MySettings.SendCloudEmailSubject = "feature-flags.co"

                    ConvertTo-Json $a -depth 100  | set-content $pathToJson

                    $pathToJsonCheck = "appsettings.json"
                    $aCheck = Get-Content $pathToJson | ConvertFrom-Json
                    Write-Host $aCheck.ConnectionStrings.ConnStr
                    Write-Host $aCheck.ConnectionStrings.RedisServerUrl
                    Write-Host $aCheck.JWT.Secret
                    Write-Host $aCheck.CosmosDb.Account
                    Write-Host $aCheck.CosmosDb.Key
                    Write-Host $aCheck.CosmosDb.DatabaseName
                    Write-Host $aCheck.CosmosDb.ContainerName
                    Write-Host $aCheck.ApplicationInsights.InstrumentationKey
                    Write-Host $aCheck.ApplicationInsights.ConnectionString
                    Write-Host $aCheck.MySettings.AppInsightsApplicationId
                    Write-Host $aCheck.MySettings.AppInsightsApplicationApiSecret.

              - task: DotNetCoreCLI@2
                displayName: dotnet restore api
                inputs:
                  command: restore
                  projects: '**/FeatureFlagsCo.APIs/FeatureFlags.APIs/FeatureFlags.APIs.csproj'
              - task: DotNetCoreCLI@2
                displayName: dotnet build api
                inputs:
                  command: 'build'
                  projects: '**/FeatureFlagsCo.APIs/FeatureFlags.APIs/FeatureFlags.APIs.csproj'
                  
              - task: DotNetCoreCLI@2
                inputs:
                  command: publish
                  publishWebProjects: True
                  arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
                  zipAfterPublish: True
              
              - task: PublishPipelineArtifact@1
                inputs:
                  targetPath: '$(Pipeline.Workspace)'
                  publishLocation: 'pipeline'