apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminportal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminportal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: adminportal
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: adminportal
        image: agiletoggle.azurecr.io/adminportal:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 150m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: adminportal
spec:
  ports:
  - port: 80
  selector:
    app: adminportal

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: adminportal
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: portal.feature-flags.co
    http:
      paths:
      - path: /
        backend:
          serviceName: adminportal
          servicePort: 80
