# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  - group: InfrastructureAsCode

stages:
  - stage: 
    displayName: 'mkdocs'
    jobs:

      - job: DeployAzureResources
        displayName: 'Deploy Resources'
        steps:
        - checkout: self

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.6'
            addToPath: true
            architecture: 'x64'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              python -c 'import sys; print(sys.version_info[:])'
              pip install mkdocs
              pip install mkdocs-material
              mkdocs build
        # - task: PythonScript@0
        #   inputs:
        #     scriptSource: 'inline'
        #     script: |
        #       python install mkdocs
        #       python install mkdocs-material
        #       mkdocs build
        
        - task: AzureFileCopy@4
          inputs:
            SourcePath: $(System.DefaultWorkingDirectory)/site/*
            azureSubscription: 'azure-china-devops'
            Destination: 'AzureBlob'
            storage: 'ffc0st0sws0mkdocs'
            ContainerName: $web
